import type { APIRoute } from "astro";
import { env } from "cloudflare:workers";
import { getConversation, putConversation } from "../../storage";
import { canonicalize, deriveTitle } from "../../parser";
import { augmentJsonlWithSubagents } from "../../parsers/jsonl";
import { json, seeOther } from "../../http";
import type { Origin } from "../../types";
import { MAX_PASTE_BYTES, MAX_PASTE_LABEL } from "../../types";

export const prerender = false;

// [LAW:one-source-of-truth] Backfill: graft supplied subagent transcript lines
// onto an existing paste's canonical claude-jsonl Origin, then re-derive its turns
// from that augmented source. Origin is the authority; the appended lines are MORE
// of the original captured after the fact (the share-slop uploader missed them, or
// they didn't exist yet) — additive capture, never a rewrite. The previously
// degraded (summary-only) subagents resolve to captured for free on re-derive.
//
// [LAW:single-enforcer] It reuses canonicalize — the SAME primitive POST /api/paste
// and POST /api/reproject use — so the augmented blob produces the same turns it
// would have produced had it been uploaded whole. And it re-stores through
// putConversation, the one writer, so lifetime/TTL semantics stay owned in one
// place. All JSONL-schema validation (session membership, subagent identity) lives
// in augmentJsonlWithSubagents; this handler is schema-blind.

// [LAW:dataflow-not-control-flow] One decode path keyed on content-type, mirroring
// /api/reproject: a JSON fetch from the page's copy-agent-prompt recipe, or a no-JS
// <form> POST. Both converge to one { slug, content } the handler acts on.
type Decoded = { readonly slug: string; readonly content: string } | null;
const decodeRequest = async (request: Request): Promise<Decoded> => {
  const ct = request.headers.get("content-type") ?? "";
  if (ct.includes("application/json")) {
    const body = (await request.json().catch(() => null)) as
      | { slug?: unknown; content?: unknown }
      | null;
    if (body && typeof body.slug === "string" && typeof body.content === "string") {
      return { slug: body.slug, content: body.content };
    }
    return null;
  }
  const form = await request.formData().catch(() => null);
  const slug = form?.get("slug");
  const content = form?.get("content");
  if (typeof slug === "string" && typeof content === "string") {
    return { slug, content };
  }
  return null;
};

const sizeOf = (s: string): number => new Blob([s]).size;

export const POST: APIRoute = async ({ request }) => {
  const wantsRedirect = !(request.headers.get("content-type") ?? "").includes("application/json");
  const decoded = await decodeRequest(request);
  if (decoded === null) return json(400, { error: "Missing or invalid 'slug' / 'content'." });

  const existing = await getConversation(env.PASTES, decoded.slug);
  if (existing === null) return json(404, { error: "No such paste." });

  // [LAW:no-silent-failure] Augment only means anything for a replayable claude-jsonl
  // origin — that is the one source kind whose blob carries reattachable subagent
  // lines. A null/editor/share/text origin has nothing to graft onto; a directly-
  // crafted request for one fails loudly here rather than silently no-op'ing.
  const origin = existing.origin;
  if (origin === null || origin.kind !== "claude-jsonl") {
    return json(409, {
      error: "This paste has no claude-jsonl origin to augment with subagent transcripts.",
    });
  }

  const augmented = augmentJsonlWithSubagents(origin.content, decoded.content);
  if (!augmented.ok) return json(422, { error: augmented.reason });

  // [LAW:single-enforcer] The same byte cap the create path applies governs the
  // augmented blob — backfill can't smuggle an arbitrarily large body into KV.
  if (sizeOf(augmented.content) > MAX_PASTE_BYTES) {
    return json(413, { error: `Augmented paste exceeds the ${MAX_PASTE_LABEL} limit.` });
  }

  // [LAW:single-enforcer] Re-derive through canonicalize so the augmented origin's
  // turns are regenerated by today's parser — the degraded subagents reattach by
  // agentId. A blob that no longer reproduces a conversation fails loudly; the
  // stored record is left untouched until the new turns are in hand.
  const newOrigin: Origin = { kind: "claude-jsonl", content: augmented.content };
  const reprojected = canonicalize(existing.turns, newOrigin);
  if (!reprojected.ok) return json(422, { error: reprojected.reason });

  // [LAW:one-source-of-truth] Replace only the derived values (turns, title) and the
  // origin we just grew; slug, createdAt, lifetime are preserved by the spread.
  const updated = {
    ...existing,
    turns: reprojected.turns,
    title: deriveTitle(reprojected.turns),
    origin: newOrigin,
  };
  await putConversation(env.PASTES, updated);

  return wantsRedirect
    ? seeOther("/" + updated.slug)
    : json(200, {
        slug: updated.slug,
        added: augmented.addedAgentIds,
        skipped: augmented.skippedAgentIds,
      });
};
